# Copyright (C) 2020 Red Hat, Inc.
#
# This program is free software: you can redistribute it and/or modify it under
# the terms of the GNU General Public License as published by the Free Software
# Foundation, either version 3 of the License, or (at your option) any later
# version.
#
# This program is distributed in the hope that it will be useful, but WITHOUT ANY
# WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A
# PARTICULAR PURPOSE.  See the GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along with
# this program.  If not, see <https://www.gnu.org/licenses/>.

---

- hosts: mon-000
  become: yes
  tasks:
  # Ignore ENOSYS from standby
  - name: flush MDS journals
    shell: ceph tell mds.* flush journal
    ignore_errors: yes

- hosts: mdss
  become: yes
  tasks:
  - name: restart mds service to drop cache
    shell:
      cmd: |
        systemctl reset-failed "ceph-{{ fsid }}@mds*"
        systemctl restart "ceph-{{ fsid }}@mds*"

- hosts: osds
  become: yes
  tasks:
  - name: restart osd service to drop cache
    shell:
      cmd: |
        systemctl reset-failed "ceph-{{ fsid }}@osd*"
        systemctl restart "ceph-{{ fsid }}@osd*"
