---

- hosts: mon-000
  become: yes
  tasks:
  - name: save uname
    shell: uname -a > uname-$(date '+%Y-%m-%d-%H-%M').txt

  - name: save status
    shell: ceph status > status-$(date '+%Y-%m-%d-%H-%M').txt

  - name: save osd tree
    shell: ceph osd tree > osd_tree-$(date '+%Y-%m-%d-%H-%M').txt

  - name: save pool ls
    shell: ceph osd pool ls detail > osd_pool_ls_detail-$(date '+%Y-%m-%d-%H-%M').txt

  - name: save pg dump
    shell: ceph pg dump > pg_dump-$(date '+%Y-%m-%d-%H-%M').txt

  - name: save df
    shell: ceph df > df-$(date '+%Y-%m-%d-%H-%M').txt

  - name: save fs dump
    shell: ceph fs dump > fs_dump-$(date '+%Y-%m-%d-%H-%M').txt

  - name: save config dump
    shell: ceph config dump > config_dump-$(date '+%Y-%m-%d-%H-%M').txt

- hosts: mons mgrs mdss osds
  become: yes
  tasks:
  - name: save sysctl
    shell: sysctl -a > sysctl-$(date '+%Y-%m-%d-%H-%M').txt

- hosts: all
  become: yes
  tasks:
  - name: save dmesg
    shell: dmesg > dmesg-$(date '+%Y-%m-%d-%H-%M').txt

  - name: save journal dump
    shell: journalctl -b > journalctl-$(date '+%Y-%m-%d-%H-%M').txt

  - name: forcibly rotate logs
    shell: logrotate -f /etc/logrotate.d/ceph
    retries: 3
    delay: 5
    register: result
    until: result.rc == 0 # handle transient failures

- import_playbook: ceph-fetch-state.yml
