# Copyright (C) 2020 Red Hat, Inc.
#
# This program is free software: you can redistribute it and/or modify it under
# the terms of the GNU General Public License as published by the Free Software
# Foundation, either version 3 of the License, or (at your option) any later
# version.
#
# This program is distributed in the hope that it will be useful, but WITHOUT ANY
# WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A
# PARTICULAR PURPOSE.  See the GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along with
# this program.  If not, see <https://www.gnu.org/licenses/>.

---

- hosts: mon-000
  become: yes
  vars:
    data_min_pgs_per_osd: 128
    replicas: 3
    dedicated_metadata_osds: osd.0 osd.1 osd.2 osd.3
  tasks:
  - name: create fs metadata pool
    shell: "ceph osd pool create cephfs_metadata replicated class-ssd-meta --size={{ replicas }}"

  - name: create fs data pool
    shell: "ceph osd pool create cephfs_data {{ data_min_pgs_per_osd }} {{ data_min_pgs_per_osd }} replicated class-ssd --size={{ replicas }} --pg_num_min={{ data_min_pgs_per_osd }}"

  - name: configure data pool target_size_ratio
    shell: "ceph osd pool set cephfs_data target_size_ratio 0.9"

  - name: create fs
    shell: "ceph fs new cephfs cephfs_metadata cephfs_data"

  - name: create client credential
    shell: "ceph fs authorize cephfs client.cephfs / rwp"
