---

- hosts: clients
  become: yes
  tasks:

  - name: install dependencies
    yum:
      name: python2-pyyaml
      state: present

  - name: clone smallfile
    git:
      repo: https://github.com/bengland2/smallfile
      dest: /root/smallfile
      update: no
