- hosts: clients
  become: yes
  tasks:
    - name: umount kcephfs
      mount:
        opts: -f -l
        state: unmounted
        path: /cephfs

    - name: set mon_addrs fact
      set_fact:
        mon_addrs: "{{ groups['mons'] | map('extract', hostvars, ['ansible_ssh_host']) | join(',') }}"

    - name: get client key secret
      shell: ceph auth print-key client.cephfs
      delegate_to: "{{ groups['mons'][0] }}"
      register: key
      run_once: true

    - name: mount kcephfs
      mount:
        boot: no
        fstype: ceph
        opts: "secret={{ key.stdout }},name=cephfs,norequire_active_mds"
        path: /cephfs
        src: "{{ mon_addrs }}:/"
        state: mounted
